# Generated by Django 4.1.5 on 2023-04-10 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upgrades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_upgrade', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('devices', models.ManyToManyField(to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Upgrade',
        ),
    ]
