# Generated by Django 4.1.5 on 2023-02-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnsName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('loginPwd', models.CharField(max_length=100)),
                ('loginUser', models.CharField(max_length=100)),
                ('deviceType', models.CharField(max_length=100)),
                ('currentVersion', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
    ]
